
waterhoogtegrootheden <- function() {
  c("Waterhoogte berekend", "Waterhoogte", "Waterhoogte astronomisch", "Waterhoogte verwacht")    
}



#' get_selected_ddl_metadata from Rijkswaterstaat data distribution layer database
#'
#' This is a function to retrieve metadata from the Rijkswaterstaaat database. 
#'
#' @param compartiment Compartment name or code (AQUO standard)
#' @param grootheid Quantity name  or code(AQUO standard)
#' @param parameter Parameter name or code(AQUO standard)
#' @param locatie Location name  or code (RWS standard)
#'
#' @returns Dataframe containing metadata selection for chosen parameters. 
#' @export
#'
#' @examples
#' 
get_selected_ddl_metadata <- function(
    compartiment = NULL, 
    grootheid = NULL, 
    parameter = NULL, 
    locatie = NULL
) {
  
  require(rwsapi)
  require(tidyverse)
  
  md <- rwsapi::rws_metadata()
  
  md$content$AquoMetadataLijst %>% 
    unnest(
      names_sep = ".", 
      c(Compartiment, Eenheid, Grootheid, Hoedanigheid, Parameter)) %>% 
    filter(
      if(is.null(grootheid)) TRUE else Grootheid.Omschrijving %in% grootheid | Grootheid.Code %in% grootheid,
      if(is.null(parameter)) TRUE else Parameter.Omschrijving %in% parameter | Parameter.Code %in% parameter,
      if(is.null(compartiment)) TRUE else Compartiment.Code %in% compartiment | Compartiment.Code %in% compartiment
    ) %>%
    left_join(
      md$content$AquoMetadataLocatieLijst, 
      by = c(AquoMetadata_MessageID = "AquoMetaData_MessageID")
    ) %>%
    left_join(md$content$LocatieLijst) %>%
    filter(if(is.null(locatie)) TRUE else Naam %in% locatie |  Code %in% locatie) %>% 
    rename_with(tolower) %>%
    rename(
      locatie.naam = naam,
      locatie.code = code
    )
}


get_selected_metadata = get_selected_ddl_metadata


#' Read water level data from Rijkswaterstaat ddl
#'
#' @param station 
#' @param startyear 
#' @param endyear 
#' @param grootheid 
#' @param outDir 
#'
#' @returns
#' @export
#'
#' @examples
readDDLwaterhoogte <- function(station, startyear, endyear, grootheid = "Waterhoogte", outDir = "data/rijkswaterstaat/ddl/raw"){
  
  require(rwsapi)
  require(tidyverse)
  
  waterhoogteparameters <- c("Waterhoogte berekend", "Waterhoogte", "Waterhoogte astronomisch", "Waterhoogte verwacht")    
  
  # make warning if grootheid is not in list of waterhoogteparameters.  
  
  md <- rwsapi::rws_metadata()
  thisCatalogue <- md$content$AquoMetadataLijst %>% 
    unnest(
      names_sep = ".", 
      c(Compartiment, Eenheid, Grootheid, Hoedanigheid, Parameter)) %>% 
    filter(Grootheid.Omschrijving == grootheid) %>%
    left_join(
      md$content$AquoMetadataLocatieLijst, 
      by = c(AquoMetadata_MessageID = "AquoMetaData_MessageID")
    ) %>%
    left_join(md$content$LocatieLijst) %>% 
    filter(Code %in% station) %>%
    rename_with(tolower) %>%
    rename(
      locatie.naam = naam,
      locatie.code = code
    )
  
  for(iyear in startyear:endyear){
    rwsapi::getDDLdata( 
      startyear = iyear,
      endyear = iyear,
      myCatalogue = thisCatalogue,
      outDir = outDir
    )
  }
}

#' Read water level data from the Rijkswaterstaat database
#'
#' @param ddlmetadata Metadata as generated by [get_selected_metadata()] 
#' @param startyear 
#' @param endyear 
#' @param outDir 
#'
#' @returns
#' @export
#'
#' @examples
#' 
#' 
#' 
readDDLwaterhoogte2 <- function(ddlmetadata, startyear, endyear, outDir = "data/rijkswaterstaat/ddl/raw"){
  
  require(rwsapi)
  require(tidyverse)
  
  waterhoogteparameters <- c("Waterhoogte berekend", "Waterhoogte", "Waterhoogte astronomisch", "Waterhoogte verwacht")    
  
  # make warning if grootheid is not in list of waterhoogteparameters.  
  
  for(iyear in startyear:endyear){
    rwsapi::getDDLdata( 
      startyear = iyear,
      endyear = iyear,
      myCatalogue = ddlmetadata,
      outDir = outDir
    )
  }
}
