
#' Title
#'
#' @param nc_path path to netcdf output generated by the Global Tide and Surge Model (GTSM). 
#' @param stations_selected GTSM ID's of monitoring stations in output file. 
#'
#' @returns
#' @export
#' @import RNetCDF
#'
#' @examples
#' 
read_gtsm_nc <- function(nc_path, stations_selected){
  
  ncf <- RNetCDF::open.nc(nc_path)
  data <- RNetCDF::read.nc(ncf)
  stations <- tibble::tibble(
    gtsmid = data$stations, 
    stationname = data$station_name,
    station_x_coordinate = data$station_x_coordinate,
    station_y_coordinate = data$station_y_coordinate
  )
  df <- reshape2::melt(data$surge, value.name = "surge_m") %>%
    dplyr::mutate(
      gtsmid = data$stations[Var2],
      month      = data$month[Var1]
    ) %>%
    dplyr::left_join(stations) %>%
    dplyr::select(-Var1, -Var2) %>%
    dplyr::filter(gtsmid %in% stations_selected)
  
  RNetCDF::close.nc(ncf)
  
  return(df)
}